version: '3.7'

networks:
  redis-net:
    driver: bridge

services:
  redis:
    image: 'redis:5.0.5'
    networks:
      - redis-net
  redis-secondary:
    image: 'redis:5.0.5'
    command: redis-server --replicaof redis 6379
    networks:
      - redis-net
  sentinel1:
    image: 'bitnami/redis-sentinel:latest'
    networks:
      - redis-net
  sentinel2:
    image: 'bitnami/redis-sentinel:latest'
    networks:
      - redis-net
  sentinel3:
    image: 'bitnami/redis-sentinel:latest'
    networks:
      - redis-net
